networks:
  integration:

volumes:
  db-data:

services:
  redis:
    image: redis:alpine
    networks:
      - integration
      
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD="muchalucha"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - integration

  worker:
    image: worker-app
    environment:
      - DB_PASS="muchalucha"
    depends_on:
      - redis
      - db
    networks:
      - integration
